server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bomb_vpn?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: bomb123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: bomb123
      database: 0

jwt:
  secret: bomb-vpn-jwt-secret-key-change-me-in-production-2026
  expire-hours: 72

alipay:
  app-id: 2021006163612029
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCUL64Tk+gc9KOmqDGKERvTAFc1f0eX0HOnZHJ6zpbf3n3w/uIK6VWxA9EwPN1jshN9BLxaWpPTnncqoj+oOIq/JfgWfZQvg5UmxihYgzVGpb8HTgP+8cMsBK1gTn3K7bj4iQe1aXrdQISW1ziaO+rFXTpgRtMk9PtDCJqzzFES+u1f39ZSTmladatxM6AlcCZgg7+GrsJVJemV5QWsuFoM5qHvbDVu67nB9SddG/icYpPxIicPGJP7JsO/Nguq8yW+5gdaF3ST3H/xOFrHNYHBaymbTg+QYHhxYmzOOXl7XCObi3eZdJgl05EPUASViQkSLuHJ00c3crxr/DSj7Eq/AgMBAAECggEADNF3CGCB8odC5Lal2mCSfJUJ9im1Yq94YaFxuafHK0ROtpsFqJX4gKBo5vhM2kPcJbNUK6isIuERQ9HXGdESR2icZi2ktNt3+munr8hhwmOx+4rHE7WMAXHCIZOIlBYuKumHjiy6oQrkrTuevNC0BTCETTGzL/41Ad5rq2PgG3kRY7ZAdt9o3ZRgWuBoQPZvLx/KgX/466SNJ+/NryJ+cpUYlK2PcBFZsRwToHDAk05o/02khAFau/gmCCJSzXhi9bo40GYSIDUqGy7tElh4WIiygVz383VQ1ArH6pOUYQevlfdrqHQdSlvXJSDRqYdORj2Mupac68368Hnviw2sSQKBgQDS+LtGad+Le24png0+83lMpA85by7DR7m2vFe9Bd4G3BzFbQRjHGrJgDa54S80fgqN/rycbxkbv/O8e7HzcoDZgA6HQQfy0Ynn9tV9Bh/IS9dTSF4oV00vy18cA+CvD/IQXhj8tVQ0j3h+WODS9dvpk1aPtEYJcwwFWMps3KyqQwKBgQCz0GwKAlwApKynBgIoPADec9epe4DKR77NLWlyEHgUjZvK/5OqJghguWw1A20xwlufRVKg51pt6659bduomXtyCZeq+Ef5xrCZIu+/TjlSonZkem3KCBy1dnq3Av9hT0cvernkQAh3hpb5j6U2TfEjwsU4YhQx9k4dm58+AItL1QKBgBMvm5hjuHiu2O3f+cRnz/gwU1Id0lrgAvujVTdTeUWWbudlaqi4xN1eU5vD5s8XR05yhCSV1eq4IipZ9Wz2VNFy299hAqAKfkgiIngkPm+wtfxU8HsqtVJLZHLfx2ckRBdI92zD8Mx237ZdztRgl4c+ZvjapCPn2ogB8ybDStCRAoGBAI0abO2d1Fyc3O9kg6TXEUd/WCkjRXl2u39+t1RPICvgw/SUgmfu2HwuhX9EZRe7EPL3D1Q8uHWxkIfVAZ5YcsqWRHJhyvlytXo2NDTHSaxS2N0YRbdYjk7H3pxmuci+0XmssNswdHR3JVpJIrhuiWAqo2EPdhGO2tXZHSkmfCjRAoGAA1cWvU7WdPRv5C7jNCJ1EJJ2+KoMczq/b/MTQqpQhvkpnyQMt0ZeWa5EzbjUTjL7W1g3wSeHHPCoMyqmYbj0ZzE/CecOQp5J4GLMigwHy5P3vbzzThsK+4a44dQo2nf/KRDBJRDjgmyJ6tr9Cu0kFJC0ljqsKXYll6znzw9XYpY=
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwadgxiupMbCYH76A5B/OmU8C/DfIkC9wGqHZuKLgDw2Lvhzs/Fb9XM2tpZN6A9enjW6XrRbT8lSybr/X86OGPlTxpy2iP+k6j4je4vjbwEl2iYLf3iFgvJGztF18WmN8/KSiNgD0E1ezwNcumeXoqARdqRewIx8d13mGGYUYeV8dBuWxtTRZ07WFAWCjx2TccpUbUZmSlMNRIy/LJ4HKwlefrb4rPOxn1ZQx1q61LngxwWrJhQ6XFlMqchl7B5sfOiPfN6S3nWdxWarzN7FtUK8JFUjEZVMvcniyrGSYeU8C+G1qmzoPdwndxBX7de5gKJ9C+fUdbKeKCyePCAFtFQIDAQAB
  gateway-url: https://openapi.alipay.com/gateway.do
  notify-url: http://fcdda56e.natappfree.cc/api/payments/alipay/notify
  return-url: http://fcdda56e.natappfree.cc/pay/result
  sandbox: false

vpn:
  wireguard:
    enabled: true
    host: 10.8.0.1
    port: 22
    username: root
    private-key-path: C:/Users/Administrator/.ssh/id_ed25519
    known-hosts-path: C:/Users/Administrator/.ssh/known_hosts
    script-path: /etc/wireguard/add-client.sh
    remove-script-path: /etc/wireguard/remove-client.sh
    connect-timeout-ms: 15000
    command-timeout-ms: 60000

bomb:
  debug:
    enabled: true

logging:
  level:
    com.bomb: debug
